name: Feature Request
description: Suggest a kernel feature or config
labels: ["enhancement"]
body:
  - type: input
    id: feature
    attributes:
      label: Feature name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What and why?
      description: What feature do you want and what problem does it solve?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Kernel config (if known)
      description: e.g. CONFIG_TCP_CONG_BBR=y
      render: ini
